<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('books')->insert([
            [
                'user_id' => 1,
                'title' => '訳あり伯爵様と契約結婚したら、義娘（６歳）の契約母になってしまいました。　〜契約期間はたったの一年間〜',
                'url' => 'https://ncode.syosetu.com/n7866hz/',
                'type_id' => 2,
                'site_name_id' => 2,
                'genre_id' => 2,
                'finish' => true ,
                'read_page' => 0,
                'all_page' => 24,
                'assessment' => 5,
                'book_color_id' => 1,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'user_id' => 1,
                'title' => '呪いで猫にされた悪女、王太子に拾われる。',
                'url' => 'https://ncode.syosetu.com/n7866hz/',
                'type_id' => 2,
                'site_name_id' => 2,
                'genre_id' => 2,
                'finish' => true ,
                'read_page' => 0,
                'all_page' => 24,
                'assessment' => 5,
                'book_color_id' => 1,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'user_id' => 1,
                'title' => '今日結婚した夫から2年経ったら出ていけと言われました',
                'url' => 'https://ncode.syosetu.com/n7866hz/',
                'type_id' => 2,
                'site_name_id' => 2,
                'genre_id' => 2,
                'finish' => true ,
                'read_page' => 0,
                'all_page' => 24,
                'assessment' => 5,
                'book_color_id' => 1,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'user_id' => 1,
                'title' => '消息を絶っていた人質姫が、見つかった。',
                'url' => 'https://ncode.syosetu.com/n7866hz/',
                'type_id' => 2,
                'site_name_id' => 2,
                'genre_id' => 2,
                'finish' => true ,
                'read_page' => 0,
                'all_page' => 24,
                'assessment' => 5,
                'book_color_id' => 1,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'user_id' => 1,
                'title' => '聖女様は「王太子殿下と結婚したいです！」と何度も要求しますが、王太子殿下はその度に「愛する婚約者と結婚出来ないくらいなら死ぬ！」と即効性のマジモンの劇薬を用意するので話が進みません。',
                'url' => 'https://ncode.syosetu.com/n7866hz/',
                'type_id' => 2,
                'site_name_id' => 2,
                'genre_id' => 2,
                'finish' => true ,
                'read_page' => 0,
                'all_page' => 24,
                'assessment' => 5,
                'book_color_id' => 1,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'user_id' => 1,
                'title' => 'ただの村人の僕が、三百年前の暴君皇子に転生してしまいました～このままでは強引に妃にする予定の冷酷侯爵令嬢に暗殺される運命なので回避するために奮闘したら、すごく溺愛されました～',
                'url' => 'https://ncode.syosetu.com/n7866hz/',
                'type_id' => 2,
                'site_name_id' => 2,
                'genre_id' => 2,
                'finish' => true ,
                'read_page' => 0,
                'all_page' => 24,
                'assessment' => 5,
                'book_color_id' => 1,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'user_id' => 1,
                'title' => 'ハズレ姫は意外と愛されている？',
                'url' => 'https://ncode.syosetu.com/n7866hz/',
                'type_id' => 2,
                'site_name_id' => 2,
                'genre_id' => 2,
                'finish' => true ,
                'read_page' => 0,
                'all_page' => 24,
                'assessment' => 5,
                'book_color_id' => 1,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'user_id' => 1,
                'title' => '魔女と傭兵',
                'url' => 'https://ncode.syosetu.com/n7866hz/',
                'type_id' => 2,
                'site_name_id' => 2,
                'genre_id' => 2,
                'finish' => true ,
                'read_page' => 0,
                'all_page' => 24,
                'assessment' => 5,
                'book_color_id' => 1,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'user_id' => 1,
                'title' => 'おひとり様には慣れましたので。',
                'url' => 'https://ncode.syosetu.com/n7866hz/',
                'type_id' => 2,
                'site_name_id' => 2,
                'genre_id' => 2,
                'finish' => true ,
                'read_page' => 0,
                'all_page' => 24,
                'assessment' => 5,
                'book_color_id' => 1,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'user_id' => 1,
                'title' => '転生幼女は前世で助けた精霊たちに懐かれる',
                'url' => 'https://ncode.syosetu.com/n7866hz/',
                'type_id' => 2,
                'site_name_id' => 2,
                'genre_id' => 2,
                'finish' => true ,
                'read_page' => 0,
                'all_page' => 24,
                'assessment' => 5,
                'book_color_id' => 1,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'user_id' => 1,
                'title' => '無能才女は悪女になりたい～義妹の身代わりで嫁いだ令嬢、公爵様の溺愛に気づかない～',
                'url' => 'https://ncode.syosetu.com/n7866hz/',
                'type_id' => 2,
                'site_name_id' => 2,
                'genre_id' => 2,
                'finish' => true ,
                'read_page' => 0,
                'all_page' => 24,
                'assessment' => 5,
                'book_color_id' => 1,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'user_id' => 1,
                'title' => '片田舎のおっさん、剣聖になる　～ただの田舎の剣術師範だったのに、大成した弟子たちが俺を放ってくれない件～',
                'url' => 'https://ncode.syosetu.com/n7866hz/',
                'type_id' => 2,
                'site_name_id' => 2,
                'genre_id' => 2,
                'finish' => true ,
                'read_page' => 0,
                'all_page' => 24,
                'assessment' => 5,
                'book_color_id' => 1,
                'created_at' => '2022/01/01 11:11:11',
            ],
        ]);
    }
}
